local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/homepage/index.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Featured title", name: "featuredTitle", widget: "string" }
          - {
              label: "Featured subtitle",
              name: "featuredSubtitle",
              widget: "string",
            }
          - { label: "Footer title", name: "footerTitle", widget: "string" }
          - {
              label: "Footer subtitle",
              name: "footerSubtitle",
              widget: "string",
            }
