local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/homepage/index.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Featured title", name: "featuredTitle", widget: "string" }
          - {
              label: "Featured subtitle",
              name: "featuredSubtitle",
              widget: "string",
            }
          - { label: "Footer title", name: "footerTitle", widget: "string" }
          - {
              label: "Footer subtitle",
              name: "footerSubtitle",
              widget: "string",
            }
  - name: "animal-category"
    label: "Animal Categories"
    folder: "src/pages/categoriesPage/data"
    format: "json"
    extension: "json"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Color", name: "color", widget: "color" }
